
spring.datasource.url=jdbc:mysql://root:IsmwpZgVeriKKcWCyYpdHkZXOfUBbEnN@gondola.proxy.rlwy.net:43065/railway
spring.datasource.username=root
spring.datasource.password=IsmwpZgVeriKKcWCyYpdHkZXOfUBbEnN